
package frc.robot.bruh;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj m1tc1 = new ChoreoTraj(
	    "m1tc1",
	    OptionalInt.empty(),
	    0.75694,
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42)),
	    new Pose2d(14.95, 3.72, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m1tc2 = new ChoreoTraj(
	    "m1tc2",
	    OptionalInt.empty(),
	    4.00642,
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42)),
	    new Pose2d(14.95, 4.32, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m1tc3 = new ChoreoTraj(
	    "m1tc3",
	    OptionalInt.empty(),
	    0.93848,
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42)),
	    new Pose2d(14.95, 4.75, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m1tp1 = new ChoreoTraj(
	    "m1tp1",
	    OptionalInt.empty(),
	    0.58034,
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42)),
	    new Pose2d(15.48, 2.1, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m1tp2 = new ChoreoTraj(
	    "m1tp2",
	    OptionalInt.empty(),
	    1.4062,
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42)),
	    new Pose2d(15.95, 7.4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m2tc1 = new ChoreoTraj(
	    "m2tc1",
	    OptionalInt.empty(),
	    0.66384,
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142)),
	    new Pose2d(14.95, 3.72, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m2tc2 = new ChoreoTraj(
	    "m2tc2",
	    OptionalInt.empty(),
	    5.08176,
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(14.95, 4.32, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m2tc3 = new ChoreoTraj(
	    "m2tc3",
	    OptionalInt.empty(),
	    0.72534,
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142)),
	    new Pose2d(14.95, 4.75, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m2tp1 = new ChoreoTraj(
	    "m2tp1",
	    OptionalInt.empty(),
	    0.93875,
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142)),
	    new Pose2d(15.48, 2.1, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m2tp2 = new ChoreoTraj(
	    "m2tp2",
	    OptionalInt.empty(),
	    1.17711,
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142)),
	    new Pose2d(15.95, 7.4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m3tc1 = new ChoreoTraj(
	    "m3tc1",
	    OptionalInt.empty(),
	    0.98512,
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425)),
	    new Pose2d(14.95, 3.72, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m3tc2 = new ChoreoTraj(
	    "m3tc2",
	    OptionalInt.empty(),
	    0.88514,
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425)),
	    new Pose2d(14.95, 4.32, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m3tc3 = new ChoreoTraj(
	    "m3tc3",
	    OptionalInt.empty(),
	    0.8084,
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425)),
	    new Pose2d(14.95, 4.75, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m3tp1 = new ChoreoTraj(
	    "m3tp1",
	    OptionalInt.empty(),
	    10.5089,
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425)),
	    new Pose2d(15.48, 2.1, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj m3tp2 = new ChoreoTraj(
	    "m3tp2",
	    OptionalInt.empty(),
	    0.7907,
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425)),
	    new Pose2d(15.95, 7.4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj s1tm1 = new ChoreoTraj(
	    "s1tm1",
	    OptionalInt.empty(),
	    0.97182,
	    new Pose2d(12.9, 0.75, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42))
	);
	public static final ChoreoTraj s1tm2 = new ChoreoTraj(
	    "s1tm2",
	    OptionalInt.empty(),
	    1.15357,
	    new Pose2d(12.9, 0.75, Rotation2d.fromRadians(0)),
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj s1tm3 = new ChoreoTraj(
	    "s1tm3",
	    OptionalInt.empty(),
	    1.47299,
	    new Pose2d(12.9, 0.75, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425))
	);
	public static final ChoreoTraj s2tm1 = new ChoreoTraj(
	    "s2tm1",
	    OptionalInt.empty(),
	    0.95459,
	    new Pose2d(13, 4, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42))
	);
	public static final ChoreoTraj s2tm2 = new ChoreoTraj(
	    "s2tm2",
	    OptionalInt.empty(),
	    0.79908,
	    new Pose2d(13, 4, Rotation2d.fromRadians(0)),
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj s2tm3 = new ChoreoTraj(
	    "s2tm3",
	    OptionalInt.empty(),
	    1.0422,
	    new Pose2d(13, 4, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425))
	);
	public static final ChoreoTraj s3tm1 = new ChoreoTraj(
	    "s3tm1",
	    OptionalInt.empty(),
	    1.40014,
	    new Pose2d(12.9, 7.45, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 2.4, Rotation2d.fromRadians(2.42))
	);
	public static final ChoreoTraj s3tm2 = new ChoreoTraj(
	    "s3tm2",
	    OptionalInt.empty(),
	    1.18242,
	    new Pose2d(12.9, 7.45, Rotation2d.fromRadians(0)),
	    new Pose2d(14.4, 4, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj s3tm3 = new ChoreoTraj(
	    "s3tm3",
	    OptionalInt.empty(),
	    0.91781,
	    new Pose2d(12.9, 7.45, Rotation2d.fromRadians(0)),
	    new Pose2d(14.85, 6.35, Rotation2d.fromRadians(-2.425))
	);
	public static final ChoreoTraj test = new ChoreoTraj(
	    "test",
	    OptionalInt.empty(),
	    0.58361,
	    new Pose2d(14, 6, Rotation2d.fromRadians(0)),
	    new Pose2d(15, 6, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("m1tc1", m1tc1),
		Map.entry("m1tc2", m1tc2),
		Map.entry("m1tc3", m1tc3),
		Map.entry("m1tp1", m1tp1),
		Map.entry("m1tp2", m1tp2),
		Map.entry("m2tc1", m2tc1),
		Map.entry("m2tc2", m2tc2),
		Map.entry("m2tc3", m2tc3),
		Map.entry("m2tp1", m2tp1),
		Map.entry("m2tp2", m2tp2),
		Map.entry("m3tc1", m3tc1),
		Map.entry("m3tc2", m3tc2),
		Map.entry("m3tc3", m3tc3),
		Map.entry("m3tp1", m3tp1),
		Map.entry("m3tp2", m3tp2),
		Map.entry("s1tm1", s1tm1),
		Map.entry("s1tm2", s1tm2),
		Map.entry("s1tm3", s1tm3),
		Map.entry("s2tm1", s2tm1),
		Map.entry("s2tm2", s2tm2),
		Map.entry("s2tm3", s2tm3),
		Map.entry("s3tm1", s3tm1),
		Map.entry("s3tm2", s3tm2),
		Map.entry("s3tm3", s3tm3),
		Map.entry("test", test)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
